In [1]:
import re
import pandas as pd

In [2]:
df = pd.read_csv("../data/processed/cases.csv")

print(df.shape)
df.head()

(31, 3)

,case_id,file_name,text_full
0,case_001,putusan_105_pdt.g_2025_pn_sda_20260624161353.pdf,penetapan nomor 105/pdt.g/2025/pn sda esi demi...
1,case_002,putusan_148_pdt.g_2025_pn_sda_20260624161238.pdf,putusan nomor 148/pdt.g/2025/pn sda demi keadi...
2,case_003,putusan_149_pdt.g_2017_pn_sda_20260624160009.pdf,direktori putusan mahkamah agung republik indo...
3,case_004,putusan_166_pdt.g_2021_pn_sda_20260624160223.pdf,direktori putusan mahkamah agung pdt.i.c.3 put...
4,case_005,putusan_213_pdt.g_2026_pn_sda_20260624160912.pdf,penetapan nomor 213/pdt.g/2026/pn sda demi kea...

In [3]:
def extract_no_perkara(text):
    pattern = r'(?:nomor\s*)?(\d+/pdt\.g/\d{4}/pn\s*sda)'
    match = re.search(pattern, text.lower())
    return match.group(1).replace(" ", "") if match else "-"

def extract_penggugat(text):
    text = text.lower()
    match = re.search(r'antara\s+(.*?)\s+lawan', text)
    return match.group(1)[:500] if match else "-"

def extract_tergugat(text):
    text = text.lower()
    match = re.search(r'lawan\s+(.*?)(?:menimbang|setelah membaca|dalam hal ini)', text)
    return match.group(1)[:500] if match else "-"

def extract_amar(text):
    text = text.lower()
    
    if "mengadili" in text:
        return text.split("mengadili")[-1][:1000]
    
    if "menetapkan" in text:
        return text.split("menetapkan")[-1][:1000]
    
    return "-"

In [4]:
df["no_perkara"] = df["text_full"].apply(extract_no_perkara)
df["penggugat"] = df["text_full"].apply(extract_penggugat)
df["tergugat"] = df["text_full"].apply(extract_tergugat)
df["amar_putusan"] = df["text_full"].apply(extract_amar)
df["jenis_perkara"] = "Wanprestasi"
df["pengadilan"] = "PN Sidoarjo"

df.head()

,case_id,file_name,text_full,no_perkara,penggugat,tergugat,amar_putusan,jenis_perkara,pengadilan
0,case_001,putusan_105_pdt.g_2025_pn_sda_20260624161353.pdf,penetapan nomor 105/pdt.g/2025/pn sda esi demi...,105/pdt.g/2025/pnsda,1. sri pudjiastuti bertempat tinggal di jalan....,1. siti rusmala bertempat tinggal di desa boha...,1. mengabulkan pencabutan permohonan perkara ...,Wanprestasi,PN Sidoarjo
1,case_002,putusan_148_pdt.g_2025_pn_sda_20260624161238.pdf,putusan nomor 148/pdt.g/2025/pn sda demi keadi...,148/pdt.g/2025/pnsda,-,les 1. kepala dinas perhubungan kabupaten sido...,nomor 415.4/34/438.5.13/2023nomor 107/lds-sdm...,Wanprestasi,PN Sidoarjo
2,case_003,putusan_149_pdt.g_2017_pn_sda_20260624160009.pdf,direktori putusan mahkamah agung republik indo...,149/pdt.g/2017/pnsda,onesi andry tejokusuma berkedudukan di jl. jem...,h. imam ghozali atau imam ghozali bertempat ti...,dalamkonpensi dalam eksepsi nkamah dalam poko...,Wanprestasi,PN Sidoarjo
3,case_004,putusan_166_pdt.g_2021_pn_sda_20260624160223.pdf,direktori putusan mahkamah agung pdt.i.c.3 put...,166/pdt.g/2021/pnsda,raditya afrisal hidayat berkedudukan di perum ...,rachmad harmoko bertempat tinggal di jalan kar...,1. menyatakan bahwa tergugat yang telah dipan...,Wanprestasi,PN Sidoarjo
4,case_005,putusan_213_pdt.g_2026_pn_sda_20260624160912.pdf,penetapan nomor 213/pdt.g/2026/pn sda demi kea...,213/pdt.g/2026/pnsda,wahjudi santoso tempat dan tanggal lahir sidoa...,avi anthy nurafni tempat dan tanggal lahir ung...,perkara ini setelah membaca penetapan hakim n...,Wanprestasi,PN Sidoarjo

In [5]:
df.to_csv("../data/processed/cases_final.csv", index=False)

print("cases_final.csv berhasil dibuat")
print(df.shape)

cases_final.csv berhasil dibuat
(31, 9)